### ISSUE TITLE
Notifed user's name is the notifier

### ISSUE THREAD

**Issue by CptnSmonge** [paviliondev/discourse-follow#1]
per--https://meta.discourse.org/t/notified-users-name-is-the-notifier/110676/13

On my own forum--
![notifier](https://user-images.githubusercontent.com/20502756/54211181-3dea9b00-44b7-11e9-976a-1bcfbb5c6143.PNG)

Occurs when you receive a like on a post. Expected behavior would be returning notifiers name, not your own.

**Comment by merefield** [comment]
Fixed as per https://meta.discourse.org/t/follow-plugin/110579/11?u=merefield
