### ISSUE TITLE
Following migration runs *every* Ruby init

### ISSUE THREAD

**Issue by blattersturm** [paviliondev/discourse-follow#27]
The migration task added in https://github.com/paviliondev/discourse-follow/commit/1612c968c43c418fe3a447b672f8846cd5cce818 runs every plugin init, doesn't save itself as already being done, and on our site with 4 million users takes 20+ minutes to run `rake db:migrate`, `rake assets:precompile` or even initialize unicorn after completing the upgrade since it unconditionally runs from plugin.rb.

**Comment by merefield** [comment]
4 million users, that's incredible, congrats!  OK I'll place it within a setting, thanks for the heads up!

**Comment by merefield** [comment]
Fixed with https://github.com/paviliondev/discourse-follow/commit/12d20c86d0d3866643fcf4249201757453abe72d
